# Generated by Django 4.0.4 on 2022-05-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='tracking_number',
            field=models.CharField(default=999481582156868, max_length=20),
        ),
    ]
